import React from 'react';
import {interpolate, staticFile, useCurrentFrame} from 'remotion';
import type {TemplateInvocationV1} from '../template-contract';

export type TemplateViewProps = {invocation: TemplateInvocationV1; assetHash: string | null};
const font = 'KurguPhase5Noto';
const copy = (value: string, color: string, size: number, extra: React.CSSProperties = {}) => <div aria-label={value} style={{fontFamily:font,color,fontSize:size,fontWeight:700,lineHeight:1.12,letterSpacing:'-0.025em',overflow:'hidden',textOverflow:'clip',...extra}}>{value}</div>;
const asset = (hash: string | null) => hash ? staticFile(`phase4a-assets/${hash.slice('sha256:'.length)}.svg`) : undefined;
const source = (hash: string | null, zoom: number) => hash ? <img alt="Trusted source binding" src={asset(hash)} style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',transform:`scale(${zoom})`}} /> : null;
const color = '#d9eff8'; const accent='#f4c854'; const ink='#111822';
const Card = ({children, invocation}: {children: React.ReactNode; invocation: TemplateInvocationV1}) => {
  const r=invocation.layout;
  return <div style={{position:'absolute',left:`${r.left_millionths/10_000}%`,top:`${r.top_millionths/10_000}%`,right:`${100-r.right_millionths/10_000}%`,bottom:`${100-r.bottom_millionths/10_000}%`,overflow:'hidden',border:'3px solid #385775',background:'#182333'}}>{children}</div>;
};
const Template = ({invocation, assetHash}: TemplateViewProps) => {
  const frame=useCurrentFrame()+invocation.start_frame; const p=interpolate(frame,[invocation.start_frame,invocation.end_exclusive_frame-1],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}); const payload=invocation.payload as Record<string, unknown>;
  const text=(key:string)=>typeof payload[key]==='string'?payload[key] as string:''; const nodes=Array.isArray(payload.nodes)?payload.nodes as {node_id:string;label:string}[]:[]; const points=Array.isArray(payload.points)?payload.points as {point_id:string;label:string;ordinal:number}[]:[];
  const head = text('headline')||text('title')||text('quote')||text('display_text')||text('label')||text('conclusion')||(text('left_label')&&`${text('left_label')} / ${text('right_label')}`)||nodes.map(node=>node.label).join(' ')||points.map(point=>point.label).join(' ');
  const body = text('body')||text('attribution')||(text('value')&&`${text('value')} ${text('qualifier')}`)||(text('left_value')&&`${text('left_value')} / ${text('right_value')} ${text('qualifier')}`);
  const sourcePanel=<div style={{position:'absolute',inset:0,background:'#253a4d'}}>{source(assetHash,1+p*.09)}<div style={{position:'absolute',inset:0,background:'linear-gradient(120deg,rgba(7,14,25,.15),rgba(7,14,25,.8))'}} /></div>;
  const targetHighlight=invocation.target_region&&<div style={{position:'absolute',left:`${invocation.target_region.left_millionths/10_000}%`,top:`${invocation.target_region.top_millionths/10_000}%`,width:`${(invocation.target_region.right_millionths-invocation.target_region.left_millionths)/10_000}%`,height:`${(invocation.target_region.bottom_millionths-invocation.target_region.top_millionths)/10_000}%`,border:`4px solid ${accent}`,pointerEvents:'none'}} />;
  if (invocation.template_id==='cold_open_source_montage') return <Card invocation={invocation}>{sourcePanel}<div style={{position:'absolute',left:40,right:40,bottom:38}}>{copy(head,accent,48)}{invocation.source_label&&copy(invocation.source_label,color,18,{marginTop:12,fontWeight:500})}</div></Card>;
  if (invocation.template_id==='article_focus_scan'||invocation.template_id==='headline_to_paragraph_zoom'||invocation.template_id==='highlight_wipe'||invocation.template_id==='news_clip_context') return <>{<Card invocation={invocation}>{sourcePanel}<div style={{position:'absolute',left:36,top:34,right:36,padding:18,background:'rgba(15,25,38,.78)',transform:`translateX(${(1-p)*(invocation.template_id==='highlight_wipe'?-120:0)}px)`}}>{copy(head,accent,36)}{body&&copy(body,color,20,{marginTop:12,fontWeight:500})}{invocation.source_label&&copy(invocation.source_label,'#93b7cc',14,{marginTop:14,fontWeight:500})}</div></Card>}{targetHighlight}</>;
  if (invocation.template_id==='chapter_title'||invocation.template_id==='final_thesis_card') return <Card invocation={invocation}><div style={{position:'absolute',inset:0,background:`linear-gradient(${120+p*20}deg,#243b55,#0b111a)`}} /><div style={{position:'absolute',left:70,right:70,top:190}}>{copy(head,accent,68)}{body&&copy(body,color,28,{marginTop:18,fontWeight:500})}</div></Card>;
  if (invocation.template_id==='expert_quote_card') return <Card invocation={invocation}><div style={{position:'absolute',inset:0,background:'#e3d9c4'}} /><div style={{position:'absolute',left:64,top:96,right:64}}>{copy(head,ink,54)}{body&&copy(body,'#54606b',25,{marginTop:24,fontWeight:500})}{invocation.source_label&&copy(invocation.source_label,'#54606b',15,{marginTop:16,fontWeight:500})}</div></Card>;
  if (invocation.template_id==='metric_reveal') return <Card invocation={invocation}><div style={{position:'absolute',inset:0,background:'#102539'}} /><div style={{position:'absolute',left:82,right:82,top:100}}>{copy(head,color,28)}<div style={{marginTop:36,transform:`scale(${.72+p*.28})`,transformOrigin:'left'}}>{copy(body,accent,96)}</div>{invocation.source_label&&copy(invocation.source_label,color,14,{marginTop:18,fontWeight:500})}</div></Card>;
  if (invocation.template_id==='metric_comparison') return <Card invocation={invocation}><div style={{display:'flex',height:'100%',gap:12,padding:52}}>{[[text('left_label'),text('left_value')],[text('right_label'),text('right_value')]].map(([label,value],index)=><div key={index} style={{flex:1,background:index?'#254562':'#183249',padding:28,transform:`translateY(${(1-p)*(index?36:-36)}px)`}}>{copy(label,color,23)}{copy(value,accent,60,{marginTop:24})}</div>)}</div></Card>;
  if (invocation.template_id==='process_diagram') return <Card invocation={invocation}><div style={{display:'flex',height:'100%',alignItems:'center',justifyContent:'space-around'}}>{nodes.map((node,index)=><React.Fragment key={node.node_id}><div style={{width:150,minHeight:88,border:`3px solid ${accent}`,padding:15,background:'#20354b'}}>{copy(node.label,color,22)}</div>{index<(nodes.length-1)&&<div style={{width:65,height:4,background:accent}} />}</React.Fragment>)}</div></Card>;
  if (invocation.template_id==='split_screen_comparison') return <Card invocation={invocation}><div style={{display:'flex',height:'100%'}}><div style={{flex:1,position:'relative',overflow:'hidden',background:'#1c3850'}}>{source(assetHash,1+p*.05)}<div style={{position:'absolute',left:30,right:30,bottom:30}}>{copy(text('left_label'),color,30)}</div></div><div style={{flex:1,background:'#513246',padding:48}}>{copy(text('right_label'),color,30)}{copy(text('conclusion'),accent,42,{marginTop:26})}</div></div></Card>;
  if (invocation.template_id==='timeline_progression') return <Card invocation={invocation}><div style={{position:'absolute',left:70,right:70,top:330,height:8,background:accent}} />{points.map((point,index)=><div key={point.point_id} style={{position:'absolute',left:`${12+index*75/(points.length-1||1)}%`,top:270,width:140}}><div style={{width:26,height:26,borderRadius:13,background:accent}} />{copy(point.label,color,19,{marginTop:14})}</div>)}</Card>;
  if (invocation.template_id==='caption_phrase') return <Card invocation={invocation}><div style={{position:'absolute',left:48,right:48,bottom:34,padding:'18px 26px',background:'rgba(8,16,27,.92)',borderLeft:`7px solid ${accent}`,transform:`translateY(${(1-p)*20}px)`}}>{copy(head,color,42)}{invocation.caption&&copy(invocation.caption,'#93b7cc',18,{marginTop:8,fontWeight:500})}</div></Card>;
  if (invocation.template_id==='kinetic_keyword') return <Card invocation={invocation}><div style={{position:'absolute',left:52,right:52,top:24,textAlign:'center',transform:`scale(${.82+p*.18})`}}>{copy(head,accent,48)}<div style={{height:5,margin:'12px auto 0',width:`${35+p*40}%`,background:accent}} /></div></Card>;
  return <Card invocation={invocation}><div style={{position:'absolute',left:80,right:80,bottom:80,transform:`scale(${.84+p*.16})`,transformOrigin:'center bottom'}}>{copy(head,accent,64)}<div style={{marginTop:12,width:`${35+p*45}%`,height:6,background:accent}} />{invocation.caption&&copy(invocation.caption,color,25,{marginTop:16,fontWeight:500})}</div></Card>;
};

export const TEMPLATE_COMPONENTS = Object.freeze({
  article_focus_scan: Template, caption_phrase: Template, chapter_title: Template, cold_open_source_montage: Template,
  expert_quote_card: Template, final_thesis_card: Template, headline_to_paragraph_zoom: Template, highlight_wipe: Template,
  kinetic_keyword: Template, metric_comparison: Template, metric_reveal: Template, news_clip_context: Template,
  process_diagram: Template, split_screen_comparison: Template, timeline_progression: Template,
});
