"""Canonical V3 models, validation, workspace, and domain-pack contracts."""

from .artifacts import validate_artifact_graph, validate_retention_policy
from .domain import (
    DomainPack,
    DomainPackError,
    DomainPackRegistry,
    DomainPolicyResolver,
    canonical_json,
    policy_snapshot_hash,
)
from .models import (
    ArtifactRecord,
    Asset,
    Beat,
    Chapter,
    DomainPackManifest,
    DomainPolicySnapshot,
    DomainProfile,
    EditorialSequence,
    EventEnvelope,
    Project,
    RetentionPolicy,
    Workspace,
)
from .narration import (
    CANONICAL_NARRATION_DOCUMENT_V1,
    NARRATION_REVISION_HASH_V1,
    NARRATION_REVISION_V1,
    NORMALIZATION_PROFILE_HASH_V1,
    CanonicalNarrationDocument,
    CanonicalNarrationMaterialization,
    CanonicalTextToken,
    CanonicalWord,
    NarrationContractError,
    NarrationParagraph,
    NarrationRejectionReason,
    NarrationRevision,
    NarrationSection,
    NarrationSentence,
    NormalizationProfileRef,
    TokenKind,
    WordRangeConsumer,
    WordRangeReference,
    materialize_canonical_narration,
    normalization_profile_hash,
    resolve_word_range,
)
from .temporal import (
    STABLE_ISSUE_CODES,
    TRP_RAW_V1,
    CanonicalRawPackage,
    RawPackageRejectionReason,
    TemporalRawPackageError,
    canonicalize_temporal_raw_package,
    load_temporal_raw_package,
    validate_issue_codes,
)
from .validation import SchemaCatalog, ValidationIssue, ValidationResult
from .workspace import LoadedWorkspace, WorkspaceLoader

__all__ = [
    "ArtifactRecord",
    "Asset",
    "Beat",
    "CANONICAL_NARRATION_DOCUMENT_V1",
    "CanonicalNarrationDocument",
    "CanonicalNarrationMaterialization",
    "CanonicalTextToken",
    "CanonicalWord",
    "Chapter",
    "DomainPack",
    "DomainPackError",
    "DomainPackManifest",
    "DomainPackRegistry",
    "DomainPolicyResolver",
    "DomainPolicySnapshot",
    "DomainProfile",
    "EditorialSequence",
    "EventEnvelope",
    "LoadedWorkspace",
    "NARRATION_REVISION_HASH_V1",
    "NARRATION_REVISION_V1",
    "NORMALIZATION_PROFILE_HASH_V1",
    "NarrationContractError",
    "NarrationParagraph",
    "NarrationRejectionReason",
    "NarrationRevision",
    "NarrationSection",
    "NarrationSentence",
    "NormalizationProfileRef",
    "Project",
    "RetentionPolicy",
    "RawPackageRejectionReason",
    "SchemaCatalog",
    "STABLE_ISSUE_CODES",
    "TRP_RAW_V1",
    "TemporalRawPackageError",
    "TokenKind",
    "ValidationIssue",
    "ValidationResult",
    "Workspace",
    "WorkspaceLoader",
    "WordRangeConsumer",
    "WordRangeReference",
    "canonical_json",
    "canonicalize_temporal_raw_package",
    "CanonicalRawPackage",
    "load_temporal_raw_package",
    "materialize_canonical_narration",
    "normalization_profile_hash",
    "policy_snapshot_hash",
    "resolve_word_range",
    "validate_artifact_graph",
    "validate_issue_codes",
    "validate_retention_policy",
]
