import {parseRenderProps} from './schema';
import {SAFE_AREA_MILLIONTHS, SAFE_AREA_POLICY, TEMPLATE_DEFINITIONS, TEMPLATE_IDS, type PayloadKind, type TemplateInvocationV1, type TemplatePayload, type TemplateRenderInputV1, type TemplateRenderPlanV1, type WordToFrameArtifactV1} from './template-contract';

const object = (v: unknown): v is Record<string, unknown> => typeof v === 'object' && v !== null && !Array.isArray(v);
const string = (v: unknown): v is string => typeof v === 'string' && v.length > 0 && v.normalize('NFC') === v;
const uint = (v: unknown): v is number => typeof v === 'number' && Number.isSafeInteger(v) && v >= 0;
const hash = (v: unknown): v is string => typeof v === 'string' && /^(?:sha256:)?[0-9a-f]{64}$/.test(v);
const exact = (v: Record<string, unknown>, keys: readonly string[], code: string) => {if (Object.keys(v).length !== keys.length || keys.some((key) => !(key in v))) throw new Error(code);};
const rectangle = (v: unknown, bounds: readonly number[], code: string) => {if (!object(v)) throw new Error(code); exact(v,['left_millionths','top_millionths','right_millionths','bottom_millionths'],code); const values=[v.left_millionths, v.top_millionths, v.right_millionths, v.bottom_millionths]; if (!values.every(uint)) throw new Error(code); const [l,t,r,b]=values as number[]; if (l >= r || t >= b || l < bounds[0] || t < bounds[1] || r > bounds[2] || b > bounds[3]) throw new Error(code); return v as TemplateInvocationV1['target_region'];};
const payload = (value: unknown, kind: PayloadKind): TemplatePayload => {
  if (!object(value)) throw new Error('TEMPLATE_PAYLOAD_INVALID'); const strings = (keys: string[]) => {exact(value,keys,'TEMPLATE_PAYLOAD_INVALID'); if (!keys.every((k) => string(value[k]))) throw new Error('TEMPLATE_PAYLOAD_INVALID');};
  switch (kind) {
    case 'SOURCE_TEXT': strings(['headline','body']); return value as TemplatePayload;
    case 'TITLE_BODY': strings(['title','body']); return value as TemplatePayload;
    case 'QUOTE': strings(['quote','attribution']); return value as TemplatePayload;
    case 'METRIC_SINGLE': strings(['label','value','qualifier']); return value as TemplatePayload;
    case 'METRIC_PAIR': strings(['left_label','left_value','right_label','right_value','qualifier']); return value as TemplatePayload;
    case 'COMPARISON': strings(['left_label','right_label','conclusion']); return value as TemplatePayload;
    case 'KINETIC': strings(['display_text']); return value as TemplatePayload;
    case 'DIAGRAM': {
      exact(value,['nodes','edges'],'TEMPLATE_PAYLOAD_INVALID'); if (!Array.isArray(value.nodes) || !Array.isArray(value.edges) || value.nodes.length === 0) throw new Error('TEMPLATE_PAYLOAD_INVALID');
      let before=''; const nodes = new Set<string>(); for (const node of value.nodes) {if (!object(node)) throw new Error('TEMPLATE_PAYLOAD_INVALID'); exact(node,['node_id','label'],'TEMPLATE_PAYLOAD_INVALID'); if (!string(node.node_id) || !string(node.label) || node.node_id <= before || nodes.has(node.node_id)) throw new Error('TEMPLATE_PAYLOAD_INVALID'); nodes.add(node.node_id); before=node.node_id;}
      for (const edge of value.edges) {if (!object(edge)) throw new Error('TEMPLATE_PAYLOAD_INVALID'); exact(edge,['from_node_id','to_node_id'],'TEMPLATE_PAYLOAD_INVALID'); if (!string(edge.from_node_id)||!string(edge.to_node_id)||!nodes.has(edge.from_node_id)||!nodes.has(edge.to_node_id)) throw new Error('TEMPLATE_PAYLOAD_INVALID');} return value as TemplatePayload;
    }
    case 'TIMELINE': {exact(value,['points'],'TEMPLATE_PAYLOAD_INVALID'); if (!Array.isArray(value.points)||value.points.length===0) throw new Error('TEMPLATE_PAYLOAD_INVALID'); let prior=''; value.points.forEach((point,index)=>{if(!object(point)) throw new Error('TEMPLATE_PAYLOAD_INVALID'); exact(point,['point_id','label','ordinal'],'TEMPLATE_PAYLOAD_INVALID'); if(!string(point.point_id)||!string(point.label)||point.point_id<=prior||point.ordinal!==index+1) throw new Error('TEMPLATE_PAYLOAD_INVALID'); prior=point.point_id;}); return value as TemplatePayload;}
  }
};
const parseWordArtifact = (v: unknown): WordToFrameArtifactV1 => {const root=['schema_version','hash_scope_version','word_to_frame_id','word_to_frame_hash','project_id','document_id','narration_revision_id','narration_revision_hash','alignment_result_id','alignment_result_hash','caption_groups_id','caption_groups_hash','emphasis_events_id','emphasis_events_hash','confidence_availability','mapping_policy_version','frame_rate','word_frames','caption_frames','emphasis_frames']; const spanKeys=['source_kind','source_id','ordinal','start_word_ordinal','end_exclusive_word_ordinal','start_word_id','end_word_id','start_ms','end_ms','start_frame','end_exclusive_frame']; if (!object(v)) throw new Error('WORD_TO_FRAME_INVALID'); exact(v,root,'WORD_TO_FRAME_INVALID'); if (v.schema_version !== 'WORD-TO-FRAME-V1'||v.hash_scope_version!=='WORD-TO-FRAME-HASH-V1'||v.mapping_policy_version!=='WORD-TO-FRAME-POLICY-V1'||!string(v.word_to_frame_id)||!hash(v.word_to_frame_hash)||!string(v.narration_revision_id)||!string(v.narration_revision_hash)||!object(v.frame_rate)||!uint(v.frame_rate.numerator)||v.frame_rate.numerator===0||!uint(v.frame_rate.denominator)||v.frame_rate.denominator===0||!Array.isArray(v.word_frames)||!Array.isArray(v.caption_frames)||!Array.isArray(v.emphasis_frames)) throw new Error('WORD_TO_FRAME_INVALID'); let prior=-1; const ids=new Set<string>(); for(const frame of v.word_frames){if(!object(frame)) throw new Error('WORD_TO_FRAME_INVALID'); exact(frame,spanKeys,'WORD_TO_FRAME_INVALID'); if(frame.source_kind!=='WORD'||!string(frame.source_id)||!string(frame.start_word_id)||!string(frame.end_word_id)||!uint(frame.ordinal)||!uint(frame.start_frame)||!uint(frame.end_exclusive_frame)||frame.start_frame>=frame.end_exclusive_frame||!uint(frame.start_word_ordinal)||!uint(frame.end_exclusive_word_ordinal)||frame.ordinal!==prior+1||frame.start_word_ordinal!==prior+1||frame.end_exclusive_word_ordinal!==frame.start_word_ordinal+1||ids.has(frame.start_word_id)||frame.start_word_id!==frame.end_word_id){throw new Error('WORD_TO_FRAME_INVALID');} prior=frame.start_word_ordinal; ids.add(frame.start_word_id);} return v as unknown as WordToFrameArtifactV1;};
const parseInvocation = (raw: unknown, input: TemplateRenderInputV1, words: WordToFrameArtifactV1): TemplateInvocationV1 => {
  if (!object(raw)) throw new Error('TEMPLATE_INVOCATION_INVALID'); exact(raw,['template_id','template_version','editorial_role','start_frame','end_exclusive_frame','layout','source_event_id','target_region','entry_animation','exit_animation','camera_motion','caption','source_label','style_preset_id','payload','word_binding','safe_area_policy'],'TEMPLATE_INVOCATION_INVALID');
  if (!TEMPLATE_IDS.includes(raw.template_id as never)||raw.template_version!=='1.0.0'||!string(raw.editorial_role)||!uint(raw.start_frame)||!uint(raw.end_exclusive_frame)||raw.start_frame>=raw.end_exclusive_frame||raw.end_exclusive_frame>input.render_props.duration_frames||!string(raw.entry_animation)||!string(raw.exit_animation)||!string(raw.camera_motion)||!string(raw.style_preset_id)||raw.safe_area_policy!==SAFE_AREA_POLICY) throw new Error('TEMPLATE_INVOCATION_INVALID');
  const definition=TEMPLATE_DEFINITIONS.find((d)=>d.template_id===raw.template_id)!; if (!definition.supported_editorial_roles.includes(raw.editorial_role as never) || raw.style_preset_id !== input.template_render_plan.style_preset.preset_id) throw new Error('TEMPLATE_INVOCATION_INVALID');
  const layout=rectangle(raw.layout, definition.kind==='KINETIC'?SAFE_AREA_MILLIONTHS.subtitle:SAFE_AREA_MILLIONTHS.content,'TEMPLATE_SAFE_AREA_INVALID');
  const target = raw.target_region === null ? null : rectangle(raw.target_region, SAFE_AREA_MILLIONTHS.content,'TEMPLATE_SAFE_AREA_INVALID'); if ((!definition.supports_target_region && target !== null) || (definition.supports_target_region && target === null)) throw new Error('TEMPLATE_INVOCATION_INVALID');
  if ((definition.requires_source_asset && !string(raw.source_event_id)) || (!definition.requires_source_asset && raw.source_event_id !== null)) throw new Error('TEMPLATE_SOURCE_INVALID'); if (string(raw.source_event_id) && !input.render_props.asset_bindings.some((binding)=>binding.event_id===raw.source_event_id)) throw new Error('TEMPLATE_SOURCE_INVALID');
  if ((definition.supports_caption ? raw.caption !== null && !string(raw.caption) : raw.caption !== null) || (definition.supports_source_label ? raw.source_label !== null && !string(raw.source_label) : raw.source_label !== null)) throw new Error('TEMPLATE_INVOCATION_INVALID');
  if (definition.supports_word_binding) {if(!object(raw.word_binding)) throw new Error('TEMPLATE_WORD_BINDING_INVALID'); exact(raw.word_binding,['narration_revision_id','word_to_frame_id','word_to_frame_hash','start_word_id','end_word_id','start_frame','end_exclusive_frame'],'TEMPLATE_WORD_BINDING_INVALID'); const b=raw.word_binding; if(!string(b.narration_revision_id)||b.narration_revision_id!==words.narration_revision_id||b.narration_revision_id!==input.render_props.narration_revision_id||b.word_to_frame_id!==words.word_to_frame_id||b.word_to_frame_id!==input.render_props.word_to_frame_id||b.word_to_frame_hash!==words.word_to_frame_hash||b.word_to_frame_hash!==input.render_props.word_to_frame_hash||!string(b.start_word_id)||!string(b.end_word_id)||!uint(b.start_frame)||!uint(b.end_exclusive_frame)||b.start_frame!==raw.start_frame||b.end_exclusive_frame!==raw.end_exclusive_frame) throw new Error('TEMPLATE_WORD_BINDING_INVALID'); const start=words.word_frames.find((word)=>word.start_word_id===b.start_word_id); const end=words.word_frames.find((word)=>word.end_word_id===b.end_word_id); if(!start||!end||start.start_word_ordinal>end.start_word_ordinal||start.start_frame!==b.start_frame||end.end_exclusive_frame!==b.end_exclusive_frame) throw new Error('TEMPLATE_WORD_BINDING_INVALID');} else if(raw.word_binding!==null) throw new Error('TEMPLATE_WORD_BINDING_INVALID');
  const result={...raw,layout,target_region:target,payload:payload(raw.payload,definition.payload_kind)} as TemplateInvocationV1; return result;
};
export const parseTemplateRenderInput = (raw: unknown): TemplateRenderInputV1 => {
  if(!object(raw)) throw new Error('TEMPLATE_INPUT_INVALID'); exact(raw,['schema_version','template_input_id','template_input_hash','render_props','template_render_plan','word_to_frame_artifact'],'TEMPLATE_INPUT_INVALID'); if(raw.schema_version!=='TEMPLATE-RENDER-INPUT-V1'||!string(raw.template_input_id)||!hash(raw.template_input_hash)) throw new Error('TEMPLATE_INPUT_INVALID'); const render_props=parseRenderProps(raw.render_props); const plan=raw.template_render_plan; if(!object(plan)) throw new Error('TEMPLATE_PLAN_INVALID'); exact(plan,['schema_version','template_plan_id','template_plan_hash','render_request_id','render_props_hash','word_to_frame_id','word_to_frame_hash','style_preset','invocations'],'TEMPLATE_PLAN_INVALID'); if(plan.schema_version!=='TEMPLATE-RENDER-PLAN-V1'||!string(plan.template_plan_id)||!hash(plan.template_plan_hash)||plan.render_request_id!==render_props.render_request_id||plan.render_props_hash!==render_props.render_props_hash||plan.word_to_frame_id!==render_props.word_to_frame_id||plan.word_to_frame_hash!==render_props.word_to_frame_hash||!object(plan.style_preset)||!Array.isArray(plan.invocations)) throw new Error('TEMPLATE_PLAN_INVALID'); const preset=plan.style_preset; exact(preset,['preset_id','color_theme_id','typography_id','font_asset_hash','tone_id','preset_hash','policy_snapshot_id','policy_snapshot_hash'],'TEMPLATE_PLAN_INVALID'); if(!['preset_id','color_theme_id','typography_id','font_asset_hash','tone_id','preset_hash'].every((key)=>string(preset[key]))||preset.typography_id!=='phase5-noto-sans-v1'||preset.font_asset_hash!=='sha256:bfb7bb691513f12e734dc346c03a03f784912432d7e3fa8e56efcf906fe86b3d'||!hash(preset.preset_hash)||(preset.policy_snapshot_id!==null&&!string(preset.policy_snapshot_id))||(preset.policy_snapshot_hash!==null&&!hash(preset.policy_snapshot_hash))) throw new Error('TEMPLATE_PLAN_INVALID'); const parsed={...raw,render_props,template_render_plan:plan,word_to_frame_artifact:parseWordArtifact(raw.word_to_frame_artifact)} as unknown as TemplateRenderInputV1; if(parsed.word_to_frame_artifact.word_to_frame_id!==render_props.word_to_frame_id||parsed.word_to_frame_artifact.word_to_frame_hash!==render_props.word_to_frame_hash||parsed.word_to_frame_artifact.narration_revision_id!==render_props.narration_revision_id||parsed.word_to_frame_artifact.frame_rate.numerator!==render_props.fps_numerator||parsed.word_to_frame_artifact.frame_rate.denominator!==render_props.fps_denominator) throw new Error('WORD_TO_FRAME_INVALID'); const invocations=plan.invocations.map((item)=>parseInvocation(item,parsed,parsed.word_to_frame_artifact)); for(let index=2;index<invocations.length;index++) if(invocations[index].template_id===invocations[index-1].template_id&&invocations[index].template_id===invocations[index-2].template_id) throw new Error('TEMPLATE_CONSECUTIVE_LIMIT'); return {...parsed,template_render_plan:{...(plan as unknown as TemplateRenderPlanV1),invocations}};
};

const canonical = (value: unknown): string => {
  if (value === null || typeof value === 'boolean' || typeof value === 'number' || typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
  if (!object(value)) throw new Error('TEMPLATE_IDENTITY_INVALID');
  return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`;
};
const sha256 = async (value: unknown): Promise<string> => {
  if (!globalThis.crypto?.subtle) throw new Error('TEMPLATE_IDENTITY_CRYPTO_UNAVAILABLE');
  const bytes = new TextEncoder().encode(canonical(value));
  const digest = await globalThis.crypto.subtle.digest('SHA-256', bytes);
  return `sha256:${Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2,'0')).join('')}`;
};
const without = (value: Record<string, unknown>, ...keys: string[]) => Object.fromEntries(Object.entries(value).filter(([key]) => !keys.includes(key)));

/** Browser-side identity defence for direct Remotion composition ingress. */
export const verifyTemplateRenderInputIdentity = async (raw: unknown): Promise<TemplateRenderInputV1> => {
  const input = parseTemplateRenderInput(raw);
  const rawInput = raw as Record<string, unknown>;
  const rawProps = rawInput.render_props as Record<string, unknown>;
  const rawPlan = rawInput.template_render_plan as Record<string, unknown>;
  const rawPreset = rawPlan.style_preset as Record<string, unknown>;
  const rawWord = rawInput.word_to_frame_artifact as Record<string, unknown>;
  const propsHash = await sha256(without(rawProps,'render_props_id','render_props_hash','render_request_id'));
  const requestHash = await sha256({schema_version:'RENDER-REQUEST-ID-V1',render_props_hash:rawProps.render_props_hash,composition_id:rawProps.composition_id,renderer_version:rawProps.renderer_version,fixture_manifest_hash:rawProps.fixture_manifest_hash});
  if (propsHash !== rawProps.render_props_hash || rawProps.render_props_id !== `rprops_${propsHash.slice(7,39)}` || rawProps.render_request_id !== `rrq_${requestHash.slice(7,39)}`) throw new Error('RENDER_PROPS_IDENTITY_INVALID');
  if (await sha256(without(rawPreset,'preset_hash')) !== rawPreset.preset_hash) throw new Error('TEMPLATE_PRESET_IDENTITY_INVALID');
  const planHash = await sha256(without(rawPlan,'template_plan_id','template_plan_hash'));
  if (planHash !== rawPlan.template_plan_hash || rawPlan.template_plan_id !== `tmplplan_${planHash.slice(7,39)}`) throw new Error('TEMPLATE_PLAN_IDENTITY_INVALID');
  const wordHash = await sha256(without(rawWord,'word_to_frame_id','word_to_frame_hash'));
  if (wordHash.slice(7) !== rawWord.word_to_frame_hash || rawWord.word_to_frame_id !== `w2f_${wordHash.slice(7,39)}`) throw new Error('WORD_TO_FRAME_IDENTITY_INVALID');
  const inputHash = await sha256(without(rawInput,'template_input_id','template_input_hash'));
  if (inputHash !== rawInput.template_input_hash || rawInput.template_input_id !== `tmplinput_${inputHash.slice(7,39)}`) throw new Error('TEMPLATE_INPUT_IDENTITY_INVALID');
  return input;
};
