"""Phase 6 source acquisition and evidence-treatment contracts."""

from .source_engine import (
    ACCESS_STATUS_FALLBACKS,
    SOURCE_CAPTURE_PLAN_V1,
    AccessStatus,
    AcquisitionAdapterId,
    AccessibleHtmlAdapter,
    ChallengeDetector,
    DOMRegion,
    DOMRegionExtractor,
    EvidenceFocusEvent,
    EvidenceFocusKind,
    EvidenceTreatmentPlan,
    EvidenceTreatmentPlanner,
    FallbackMode,
    FeedApiAdapter,
    ManualCaptureAdapter,
    ManualCapturePackage,
    OfficialPdfAdapter,
    PlannerGateDecision,
    ReplaySourcePackage,
    SourceAcquisitionError,
    SourceAdapterRegistry,
    SourceCapturePlan,
    SourcePriorityPolicy,
    SourcePreviewRenderer,
    SourceType,
    gate_primary_source_requirement,
    rank_source_packages,
    source_priority_policy_from_snapshot,
)

__all__ = [
    "ACCESS_STATUS_FALLBACKS", "SOURCE_CAPTURE_PLAN_V1", "AccessStatus",
    "AcquisitionAdapterId", "AccessibleHtmlAdapter", "ChallengeDetector",
    "DOMRegion", "DOMRegionExtractor", "EvidenceFocusEvent",
    "EvidenceFocusKind", "EvidenceTreatmentPlan", "EvidenceTreatmentPlanner",
    "FallbackMode", "FeedApiAdapter", "ManualCaptureAdapter", "ManualCapturePackage", "OfficialPdfAdapter",
    "PlannerGateDecision", "ReplaySourcePackage", "SourceAcquisitionError",
    "SourceAdapterRegistry", "SourceCapturePlan", "SourcePriorityPolicy",
    "SourcePreviewRenderer", "SourceType", "gate_primary_source_requirement",
    "rank_source_packages",
    "source_priority_policy_from_snapshot",
]
