"""Phase 6 source acquisition and evidence-treatment contracts."""

from .source_engine import (
    ACCESS_STATUS_FALLBACKS,
    SOURCE_CAPTURE_PLAN_V1,
    AccessStatus,
    AcquisitionAdapterId,
    AccessibleHtmlAdapter,
    ChallengeDetector,
    DOMRegion,
    DOMRegionExtractor,
    EvidenceFocusEvent,
    EvidenceFocusKind,
    EvidenceTreatmentPlan,
    EvidenceTreatmentPlanner,
    FallbackMode,
    FeedApiAdapter,
    ManualCaptureAdapter,
    ManualCapturePackage,
    OfficialPdfAdapter,
    PlannerGateDecision,
    ReplaySourcePackage,
    SourceAcquisitionError,
    SourceAdapterRegistry,
    SourceCapturePlan,
    SourcePriorityPolicy,
    SourcePreviewRenderer,
    SourceType,
    gate_primary_source_requirement,
    rank_source_packages,
    source_priority_policy_from_snapshot,
)
from .asset_catalog import (
    ASSET_CATALOG_POLICY_V1,
    AssetBriefV1,
    AssetCatalogError,
    AssetRecordV1,
    AssetIngestionPackageV1,
    CatalogFailureV1,
    AssetCatalogMutationV1,
    AssetCatalogPolicyV1,
    AssetCatalogV1,
    AssetIngestionInputV1,
    AssetMaterializationRegistry,
    AssetReuseContextV1,
    AssetReuseInstanceV1,
    AssetReusePlanV1,
    AssetReuseViolationV1,
    CatalogReceiptV1,
    DuplicateKind,
    DuplicateDecisionV1,
    FingerprintEvidenceV1,
    MediaProbeEvidenceV1,
    MediaType,
    GenericStockRatioV1,
    ReplayAssetEvidenceRegistry,
    SelectedRangeV1,
    SemanticDeclarationV1,
    SourceAudioEligibilityV1,
    SourceAudioStatus,
    SourceDescriptorV1,
    asset_catalog_policy_from_snapshot,
    compile_asset_catalog,
    canonical_asset_catalog_json,
    canonical_catalog_mutation_json,
    canonical_catalog_receipt_json,
    canonical_ingestion_package_json,
    evaluate_asset_reuse,
    empty_asset_catalog,
    load_asset_catalog_json,
    load_catalog_mutation_json,
    load_catalog_receipt_json,
    load_ingestion_package_json,
    verify_catalog_receipt,
)

__all__ = [
    "ACCESS_STATUS_FALLBACKS", "SOURCE_CAPTURE_PLAN_V1", "AccessStatus",
    "AcquisitionAdapterId", "AccessibleHtmlAdapter", "ChallengeDetector",
    "DOMRegion", "DOMRegionExtractor", "EvidenceFocusEvent",
    "EvidenceFocusKind", "EvidenceTreatmentPlan", "EvidenceTreatmentPlanner",
    "FallbackMode", "FeedApiAdapter", "ManualCaptureAdapter", "ManualCapturePackage", "OfficialPdfAdapter",
    "PlannerGateDecision", "ReplaySourcePackage", "SourceAcquisitionError",
    "SourceAdapterRegistry", "SourceCapturePlan", "SourcePriorityPolicy",
    "SourcePreviewRenderer", "SourceType", "gate_primary_source_requirement",
    "rank_source_packages",
    "source_priority_policy_from_snapshot",
    "ASSET_CATALOG_POLICY_V1", "AssetBriefV1", "AssetCatalogError", "CatalogFailureV1", "AssetCatalogMutationV1", "AssetCatalogPolicyV1",
    "AssetCatalogV1", "AssetRecordV1", "AssetIngestionInputV1", "AssetIngestionPackageV1", "AssetMaterializationRegistry",
    "AssetReuseContextV1", "AssetReuseInstanceV1", "AssetReusePlanV1", "AssetReuseViolationV1", "CatalogReceiptV1", "DuplicateKind", "DuplicateDecisionV1",
    "FingerprintEvidenceV1", "MediaProbeEvidenceV1", "MediaType", "GenericStockRatioV1",
    "ReplayAssetEvidenceRegistry", "SelectedRangeV1", "SemanticDeclarationV1",
    "SourceAudioEligibilityV1", "SourceAudioStatus", "SourceDescriptorV1",
    "asset_catalog_policy_from_snapshot", "compile_asset_catalog",
    "canonical_asset_catalog_json", "evaluate_asset_reuse", "empty_asset_catalog",
    "canonical_catalog_mutation_json", "canonical_catalog_receipt_json", "canonical_ingestion_package_json",
    "load_asset_catalog_json", "load_catalog_mutation_json", "load_catalog_receipt_json", "load_ingestion_package_json", "verify_catalog_receipt",
]
